"$schema" = 'https://starship.rs/config-schema.json'

format = """$os$username in $directory$git_branch$git_status$bun$c$cmake$cobol$crystal$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$gradle$guix_shell$haskell$haxe$helm$java$julia$kotlin$lua$maven$meson$mojo$nim$nodejs$ocaml$odin$opa$perl$php$pixi$pulumi$purescript$python$raku$red$rlang$ruby$rust$scala$singularity$solidity$spack$swift$terraform$typst$vagrant$vlang$xmake$zig$aws$gcloud$openstack$azure$conda$direnv$docker_context$kubernetes$package$buf$nix_shell$cmd_duration
$character"""



[character]
success_symbol = '[❯](bold #FFF0C4)'
error_symbol = '[❯](bold #E05C5C)'

[os]
style = '#660B05'
disabled = false

[username]
style_user = '#FFF0C4'
format = '[$user]($style)'
show_always = true

[git_status]
modified = '[✎](fg:#E05C5C)'
untracked = '[?](fg:#D4A84B)'

[cmd_duration]
style = '#D4A84B'



[aws]
symbol = " "
style = 'bold #660B05'
[azure]
symbol = " "
style = 'bold #660B05'
[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
[buf]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[bun]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[c]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[cpp]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[cmake]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[cobol]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[conda]
symbol = " "
style = 'bold #660B05'
[container]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[crystal]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[dart]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[deno]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[direnv]
symbol = " "
style = 'bold #660B05'
[directory]
read_only = " 󰌾"
style = '#E05C5C'
[docker_context]
symbol = " "
style = 'bold #660B05'
[dotnet]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[elixir]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[elm]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[erlang]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[fennel]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[fortran]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[fossil_branch]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[gcloud]
symbol = "󱇶 "
style = 'bold #660B05'
[gleam]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[git_branch]
format = '[$symbol]($style)[$branch(:$remote_branch)](bold #FFF0C4) '
truncation_length = 20
truncation_symbol = '…'
symbol = " "
style = 'bold #660B05'
[git_commit]
tag_symbol = '  '
[golang]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[gradle]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[guix_shell]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[haskell]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[haxe]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[helm]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[hg_branch]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'
ssh_symbol = " "
style = '#C4724A'
[java]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[julia]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[kotlin]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[kubernetes]
symbol = "󱃾 "
style = 'bold #660B05'
[lua]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[maven]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[memory_usage]
symbol = "󰍛 "
style = 'bold #660B05'
[meson]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󰔷 "
style = 'bold #660B05'
[mojo]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󰈸 "
style = 'bold #660B05'
[nats]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[netns]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󰛳 "
style = 'bold #660B05'
[nim]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[nix_shell]
symbol = " "
style = 'bold #660B05'
[nodejs]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[ocaml]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[odin]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󰟢 "
style = 'bold #660B05'
[opa]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[openstack]
symbol = " "
style = 'bold #660B05'
[os.symbols]
AIX = " "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
InstantOS = " "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰺡 "
PikaOS = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = "󰍲 "
Zorin = " "


[package]
format = 'is [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󰏗 "
style = 'bold #660B05'
[perl]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[php]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[pijul_channel]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[pixi]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󰏗 "
style = 'bold #660B05'
[pulumi]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[purescript]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[python]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[raku]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󱖊 "
style = 'bold #660B05'
[red]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󱍼 "
style = 'bold #660B05'
[rlang]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󰟔 "
style = 'bold #660B05'
[ruby]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[rust]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󱘗 "
style = 'bold #660B05'
[scala]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[shlvl]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = "󰹍 "
style = 'bold #660B05'
[singularity]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[solidity]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[spack]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[status]
symbol = " "
style = '#E05C5C'
disabled = false
[sudo]
symbol = " "
style = 'bold #660B05'
[swift]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[terraform]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[vlang]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[typst]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[vagrant]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[xmake]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'
[zig]
format = 'via [$symbol](bold #660B05)[$version ](bold #FFF0C4)'
symbol = " "
style = 'bold #660B05'