local hotkeyCmd1 = hs.hotkey.bind({"cmd"}, "1", function()
  hs.application.launchOrFocus("iTerm")
end)

hs.hotkey.bind({"cmd"}, "2", function()
  hs.application.launchOrFocus("Firefox")
end)

hs.hotkey.bind({"cmd", "shift"}, "v", function()
  hs.eventtap.keyStroke({"cmd"}, "space")
  hs.timer.doAfter(0.2, function()
    hs.eventtap.keyStroke({"cmd"}, "4")
  end)
end)

hs.hotkey.bind({"cmd", "shift"}, "space", function()
  hs.eventtap.keyStroke({"cmd"}, "space")
  hs.timer.doAfter(0.2, function()
    hotkeyCmd1:disable()
    hs.eventtap.keyStroke({"cmd"}, "1")
    hs.timer.doAfter(0.1, function()
      hotkeyCmd1:enable()
    end)
  end)
end)
